# Generated by Django 6.0.6 on 2026-07-06 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('capital', models.FloatField()),
                ('comision', models.FloatField()),
                ('tasa_venta', models.FloatField()),
                ('tasa_compra', models.FloatField()),
                ('ciclos_dia', models.IntegerField(default=1)),
                ('metodos_pago', models.IntegerField(default=1)),
                ('monto_venta', models.FloatField()),
                ('monto_compra', models.FloatField()),
                ('ganancia_porcentaje', models.FloatField()),
                ('ganancia_ciclo', models.FloatField()),
                ('ganancia_diaria', models.FloatField()),
                ('ganancia_mensual', models.FloatField()),
                ('tasa_minima_compra', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
