# Generated by Django 6.0.6 on 2026-07-06 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_dailylog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailylog',
            options={'ordering': ['-date', 'id']},
        ),
        migrations.AddField(
            model_name='calculation',
            name='comision_compra',
            field=models.FloatField(default=0.35),
        ),
        migrations.AddField(
            model_name='calculation',
            name='comision_venta',
            field=models.FloatField(default=0.35),
        ),
        migrations.AddField(
            model_name='calculation',
            name='metodo_compra',
            field=models.CharField(default='Zinli', max_length=50),
        ),
        migrations.AddField(
            model_name='calculation',
            name='metodo_venta',
            field=models.CharField(default='Zinli', max_length=50),
        ),
        migrations.AddField(
            model_name='calculation',
            name='plataforma_compra',
            field=models.CharField(default='Binance P2P', max_length=50),
        ),
        migrations.AddField(
            model_name='calculation',
            name='plataforma_venta',
            field=models.CharField(default='Binance P2P', max_length=50),
        ),
        migrations.AddField(
            model_name='calculation',
            name='tasa_retorno',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='calculation',
            name='tipo_operativa',
            field=models.CharField(default='USD', max_length=20),
        ),
        migrations.AddField(
            model_name='dailylog',
            name='comision_compra',
            field=models.FloatField(default=0.35),
        ),
        migrations.AddField(
            model_name='dailylog',
            name='comision_venta',
            field=models.FloatField(default=0.35),
        ),
        migrations.AddField(
            model_name='dailylog',
            name='metodo_compra',
            field=models.CharField(default='Zinli', max_length=50),
        ),
        migrations.AddField(
            model_name='dailylog',
            name='metodo_venta',
            field=models.CharField(default='Zinli', max_length=50),
        ),
        migrations.AddField(
            model_name='dailylog',
            name='plataforma_compra',
            field=models.CharField(default='Binance P2P', max_length=50),
        ),
        migrations.AddField(
            model_name='dailylog',
            name='plataforma_venta',
            field=models.CharField(default='Binance P2P', max_length=50),
        ),
        migrations.AddField(
            model_name='dailylog',
            name='tipo_operativa',
            field=models.CharField(default='USD', max_length=20),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='comision',
            field=models.FloatField(default=0.35),
        ),
        migrations.AlterField(
            model_name='dailylog',
            name='date',
            field=models.DateField(),
        ),
    ]
