# Generated by Django 6.0.6 on 2026-07-06 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0003_alter_dailylog_options_calculation_comision_compra_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('platform', models.CharField(max_length=50)),
                ('currency', models.CharField(choices=[('USDT', 'USDT (Tether)'), ('USD', 'USD (Dólar)'), ('VES', 'VES (Bolívares)')], max_length=10)),
                ('balance', models.FloatField(default=0.0)),
                ('is_active', models.BooleanField(default=True)),
                ('color', models.CharField(default='#2563eb', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['platform', 'currency'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('type', models.CharField(choices=[('VENTA_P2P', 'Venta P2P'), ('COMPRA_P2P', 'Compra P2P'), ('DEPOSITO', 'Depósito'), ('RETIRO', 'Retiro'), ('TRANSFERENCIA', 'Transferencia')], max_length=20)),
                ('amount_out', models.FloatField(default=0.0)),
                ('amount_in', models.FloatField(default=0.0)),
                ('rate', models.FloatField(default=1.0)),
                ('commission_pct', models.FloatField(default=0.0)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wallet_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions_out', to='calculator.wallet')),
                ('wallet_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions_in', to='calculator.wallet')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
