# Generated by Django 6.0.3 on 2026-07-08 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0006_dedupe_wallets_unique_identity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculation',
            name='capital',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='comision',
            field=models.DecimalField(decimal_places=4, default=0.35, max_digits=6),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='comision_compra',
            field=models.DecimalField(decimal_places=4, default=0.35, max_digits=6),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='comision_venta',
            field=models.DecimalField(decimal_places=4, default=0.35, max_digits=6),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='ganancia_ciclo',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='ganancia_diaria',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='ganancia_mensual',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='ganancia_porcentaje',
            field=models.DecimalField(decimal_places=4, max_digits=8),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='monto_compra',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='monto_venta',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='tasa_compra',
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='tasa_minima_compra',
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='tasa_retorno',
            field=models.DecimalField(decimal_places=4, default=1.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='tasa_venta',
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
        migrations.AlterField(
            model_name='dailylog',
            name='comision_compra',
            field=models.DecimalField(decimal_places=4, default=0.35, max_digits=6),
        ),
        migrations.AlterField(
            model_name='dailylog',
            name='comision_venta',
            field=models.DecimalField(decimal_places=4, default=0.35, max_digits=6),
        ),
        migrations.AlterField(
            model_name='dailylog',
            name='profit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='dailylog',
            name='volume',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount_in',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount_out',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='commission_pct',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='rate',
            field=models.DecimalField(decimal_places=4, default=1.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='opening_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14),
        ),
    ]
