# Generated by Django 6.0.3 on 2026-07-09 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0007_alter_calculation_capital_alter_calculation_comision_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='dailylog',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
