# Generated by Django 6.0.7 on 2026-07-12 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0008_alter_calculation_created_at_alter_dailylog_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='category',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('VENTA_P2P', 'Venta P2P'), ('COMPRA_P2P', 'Compra P2P'), ('DEPOSITO', 'Depósito'), ('RETIRO', 'Retiro'), ('TRANSFERENCIA', 'Transferencia'), ('GASTO', 'Gasto Operativo'), ('INGRESO_EXTERNO', 'Ingreso Externo')], max_length=20),
        ),
    ]
