# Generated by Django 6.0.7 on 2026-07-19 19:23

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0009_transaction_category_alter_transaction_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calculation',
            name='comision',
        ),
        migrations.AlterField(
            model_name='calculation',
            name='comision_compra',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.35'), max_digits=6),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='comision_venta',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.35'), max_digits=6),
        ),
        migrations.AlterField(
            model_name='dailylog',
            name='comision_compra',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.35'), max_digits=6),
        ),
        migrations.AlterField(
            model_name='dailylog',
            name='comision_venta',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.35'), max_digits=6),
        ),
    ]
